#!/bin/sh

SCALA212_VERSION="$(grep -oP '(?<=def scala212 = ")[^"]*(?<!")' project/Settings.scala)"
SCALA211_VERSION="$(grep -oP '(?<=def scala211 = ")[^"]*(?<!")' project/Settings.scala)"

docker build --build-arg SCALA_VERSIONS="$SCALA211_VERSION $SCALA212_VERSION" -t $IMAGE_NAME .
docker build --build-arg SCALA_VERSIONS="$SCALA211_VERSION" -t $IMAGE_NAME-$SCALA211_VERSION .
docker build --build-arg SCALA_VERSIONS="$SCALA212_VERSION" -t $IMAGE_NAME-$SCALA212_VERSION .